openapi: 3.0.0
info:
  title: app
  version: 1.0
tags:
  - name: hello
  - name: bye
paths:
  /v1/hello:
    $ref: ./paths/v1/hello/index.yaml
  /v1/bye:
    $ref: ./paths/v1/bye/index.yaml
components:
  schemas:
    HelloDTO:
      # $ref: ./components/schemas/HelloDTO.yaml
      $ref: /Users/hytssk/Work/java/SpringBootMicroServiceTutorial/appApiSchema/components/schemas/HelloDTO.yaml
    ByeDTO:
      # $ref: ./components/schemas/ByeDTO.yaml
      $ref: /Users/hytssk/Work/java/SpringBootMicroServiceTutorial/appApiSchema/components/schemas/ByeDTO.yaml
