name: dagger-test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: dagger/dagger-for-github@v3
        with:
          version: 0.2.9
          workdir: ./dagger
          cmds: |
            do push --log-format=plain
